import Head from "next/head";
import Image from "next/image";
import { Avatar, Text, Button, Card } from "dracula-ui";
import SocialList from "components/social-list";
import Typewriter from "typewriter-effect";
import { motion } from "framer-motion";
const styles = {
  container: "max-w-desktop px-10 w-full",
  text: "text-2xl mb-2",
};
const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Jonathan Picazo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className="home w-full h-screen flex items-center justify-center">
        <div className="w-full">
          <section className="flex flex-col items-center justify-center">
            <div className="flex flex-col py-3">
              <Image
                className="rounded-full"
                src="/images/pfp.jpeg"
                alt="green"
                width={250}
                height={250}
              />
            </div>
            <p className={`${styles.text}`}>Jonathan Picazo</p>
            <div className={styles.text}>
              <Typewriter
                options={{
                  strings: [
                    "Web Developer",
                    "Software Engineer",
                    "Dracula Enjoyer",
                    "Builder",
                  ],
                  autoStart: true,
                  loop: true,
                }}
              />
            </div>
            <SocialList />
            <div>
              <div>
                <motion.button
                  className="p-5 border border-dracula-cyan rounded-xl"
                  /**
                   * Setting the initial keyframe to "null" will use
                   * the current value to allow for interruptable keyframes.
                   */
                  whileHover={{ scale: [null, 1.5, 1.4] }}
                  transition={{ duration: 0.3 }}
                >
                  Download
                </motion.button>
              </div>
            </div>
          </section>
        </div>
      </main>
    </div>
  );
};

export default Home;
