import Head from "next/head";
import Image from "next/image";
import { Avatar, Text, Button, Card } from "dracula-ui";
import SocialList from "components/social-list";
import Typewriter from "typewriter-effect";
import { motion } from "framer-motion";
import { FaDownload } from "react-icons/fa";
const Home = () => {
  return (
    <div className="max-w-desktop px-10 w-full mx-auto">
      <Head>
        <title>Jonathan Picazo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className="home w-full h-screen flex items-center justify-center">
        <div className="w-full">
          <section className="flex flex-col items-center justify-center">
            <div className="flex flex-col py-3">
              <Image
                className="rounded-full mb-5 "
                src="/images/pfp.jpeg"
                alt="green"
                width={250}
                height={250}
                loading="eager"
              />
            </div>
            <h1 className="mb-4 text-2xl md:text-4xl font-bold text-body">
              Jonathan Picazo
            </h1>
            <div className="text-large md:text-xl mb-2">
              <Typewriter
                options={{
                  strings: [
                    "Web Developer",
                    "Software Engineer",
                    "Dracula Enjoyer",
                    "Builder",
                  ],
                  autoStart: true,
                  loop: true,
                }}
              />
            </div>
            <SocialList />
            <div>
              <div>
                <motion.div
                  /**
                   * Setting the initial keyframe to "null" will use
                   * the current value to allow for interruptable keyframes.
                   */
                  whileHover={{ scale: [null, 1.3, 1.2] }}
                  transition={{ duration: 0.3 }}
                >
                  <a
                    className="p-5 border border-dracula-cyan bg-dracula-darker hover:opacity-75 rounded-3xl flex items-center gap-x-5"
                    role="button"
                    href="/picazo_cv.pdf"
                    download="CV_Jonathan_Picazo.pdf"
                  >
                    <FaDownload className="text-dracula-cyan" />
                    <span className="text-dracula-cyan">Download CV</span>
                  </a>
                </motion.div>
              </div>
            </div>
          </section>
        </div>
      </main>
    </div>
  );
};

export default Home;
